In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('src/data/train.csv')

In [21]:
df.columns

Index(['patient_id', 'site_id', 'triage_nurse_id', 'arrival_mode',
       'arrival_hour', 'arrival_day', 'arrival_month', 'arrival_season',
       'shift', 'age', 'age_group', 'sex', 'language', 'insurance_type',
       'transport_origin', 'pain_location', 'mental_status_triage',
       'chief_complaint_system', 'num_prior_ed_visits_12m',
       'num_prior_admissions_12m', 'num_active_medications',
       'num_comorbidities', 'systolic_bp', 'diastolic_bp',
       'mean_arterial_pressure', 'pulse_pressure', 'heart_rate',
       'respiratory_rate', 'temperature_c', 'spo2', 'gcs_total', 'pain_score',
       'weight_kg', 'height_cm', 'bmi', 'shock_index', 'news2_score',
       'disposition', 'ed_los_hours', 'triage_acuity'],
      dtype='str')

In [9]:
df['sex'].unique()

<ArrowStringArray>
['M', 'F', 'Other']
Length: 3, dtype: str

In [16]:
df['insurance_type'].unique()

<ArrowStringArray>
['public', 'military', 'none', 'private', 'unknown']
Length: 5, dtype: str

In [17]:
df['transport_origin'].unique()

<ArrowStringArray>
[  'public_space',           'home',   'nursing_home',        'outdoor',
      'workplace', 'other_hospital',         'school']
Length: 7, dtype: str

In [18]:
df['pain_location'].unique()

<ArrowStringArray>
['extremity',   'abdomen',  'multiple',      'back',   'unknown',      'head',
     'chest',      'none',    'pelvis']
Length: 9, dtype: str

In [19]:
df['mental_status_triage'].unique()

<ArrowStringArray>
['drowsy', 'alert', 'unresponsive', 'agitated', 'confused']
Length: 5, dtype: str

In [ ]:
df['a'].unique()

<ArrowStringArray>
[ 'Finnish',  'Russian',  'English',   'Arabic', 'Estonian',   'Somali',
  'Swedish',    'Other']
Length: 8, dtype: str

In [15]:
df['age_group'].unique()

<ArrowStringArray>
['middle_aged', 'elderly', 'young_adult', 'pediatric']
Length: 4, dtype: str

In [10]:
df.head()

,patient_id,site_id,triage_nurse_id,arrival_mode,arrival_hour,arrival_day,arrival_month,arrival_season,shift,age,...,gcs_total,pain_score,weight_kg,height_cm,bmi,shock_index,news2_score,disposition,ed_los_hours,triage_acuity
0,TG-UXRGA9UCO,SITE-TMP-01,NURSE-0033,walk-in,6,Monday,5,spring,morning,43,...,14,7,52.3,165.4,19.1,0.725,8,discharged,7.35,2
1,TG-B19DBBS2G,SITE-HEL-01,NURSE-0001,walk-in,6,Thursday,4,spring,morning,72,...,15,-1,73.3,164.4,27.1,0.739,1,discharged,0.70,5
2,TG-GZ97W7M6V,SITE-HEL-02,NURSE-0005,walk-in,8,Saturday,4,spring,morning,82,...,15,3,77.1,183.7,22.8,0.798,2,discharged,0.63,5
3,TG-THIB2TN9Q,SITE-HEL-02,NURSE-0026,police,7,Sunday,3,spring,morning,50,...,15,7,49.6,172.6,16.6,0.812,2,discharged,1.99,3
4,TG-J3U3LQ2QY,SITE-HEL-02,NURSE-0044,walk-in,5,Tuesday,5,spring,night,62,...,15,4,71.9,173.4,23.9,0.812,2,transferred,3.58,3

In [6]:
cheif_c = pd.read_csv('data/chief_complaints.csv')

In [13]:
cheif_c.head()

,patient_id,chief_complaint_raw,chief_complaint_system
0,TG-UXRGA9UCO,"thunderclap headache, worsening with movement",neurological
1,TG-B19DBBS2G,"contraception advice, intermittent",genitourinary
2,TG-GZ97W7M6V,"general health question, intermittent",other
3,TG-THIB2TN9Q,"erythema migrans tick bite, intermittent",dermatological
4,TG-J3U3LQ2QY,"cellulitis localised, intermittent",dermatological

In [8]:
patient_records = pd.read_csv('data/patient_history.csv')

In [14]:
patient_records.columns

Index(['patient_id', 'hx_hypertension', 'hx_diabetes_type2',
       'hx_diabetes_type1', 'hx_asthma', 'hx_copd', 'hx_heart_failure',
       'hx_atrial_fibrillation', 'hx_ckd', 'hx_liver_disease', 'hx_malignancy',
       'hx_obesity', 'hx_depression', 'hx_anxiety', 'hx_dementia',
       'hx_epilepsy', 'hx_hypothyroidism', 'hx_hyperthyroidism', 'hx_hiv',
       'hx_coagulopathy', 'hx_immunosuppressed', 'hx_pregnant',
       'hx_substance_use_disorder', 'hx_coronary_artery_disease',
       'hx_stroke_prior', 'hx_peripheral_vascular_disease'],
      dtype='str')